### ISSUE TITLE
ng add ng-zorro-antd执行报错，报下载下来了，但是没有把配置文件和APModule修改

### ISSUE THREAD

**Issue by crashsol** [NG-ZORRO/today-ng-steps#1]
Excute： ng add ng-zorro-antd
错误提示：
Installing packages for tooling via npm.
undefined does not have an architect configuration
查看package.json 
"ng-zorro-antd": "^1.5.0",是安装了的，是需要手动去配置APPModule么？

**Comment by wzhudev** [comment]
@crashsol 新版本的 schematic 出了点问题, 在修了. 你现在可以手动配置一下 `app.module.ts` 文件, 官网上有说明.

**Comment by crashsol** [comment]
好的，谢谢

**Comment by crashsol** [comment]
当我创建项目，手动把angular.json 里面的 targets 修改为architect，然后在执行 ng add ng-zorro-antd就成功了

**Comment by wendzhue** [comment]
Ref https://github.com/NG-ZORRO/ng-zorro-antd/pull/2131.
