### ISSUE TITLE
安装命令缺少

### ISSUE THREAD

**Issue by tao996** [NG-ZORRO/today-ng-steps#18]
官方[实战教程](https://github.com/NG-ZORRO/today-ng-steps/blob/master/tutorial/1.md)安装项目的命令

```
$ ng new today-ng
$ cd today-ng
$ ng add ng-zorro-antd
```

如果没有先执行 `cnpm install --save ng-zorro-antd` 而直接执行 `ng add ng-zorro-antd`，则会提示`Could not find module "ng-zorro-antd"`

**Comment by wzhudev** [comment]
@lvshutao Angular cli 遇到 cnpm 经常会发生莫名其妙的问题, 使用 npm + nrm.

检查一下你的开发环境的问题.
