### ISSUE TITLE
Wrong file name in today-ng tutorial

### ISSUE THREAD

**Issue by Indomi** [NG-ZORRO/today-ng-steps#20]
![day 1](https://i.loli.net/2018/11/09/5be4ef22efce6.jpg)
I think it should be setup.component.html instead of setup.module.html ?
我觉得这里应该是setup.component.html而不是setup.module.html把?按照命令自动生成的话

**Comment by wzhudev** [comment]
@Indomi 是的，之前有个同学提过相关的 PR https://github.com/NG-ZORRO/today-ng-steps/pull/19/files

你愿意提个 PR 来修改吗？
