### ISSUE TITLE
ngModel  error

### ISSUE THREAD

**Issue by qpb** [NG-ZORRO/today-ng-steps#21]
<input nz-input placeholder="请输入你喜欢的用户名" #usernameInput [(ngModel)]="username">

报错：Can't bind to 'ngModel' since it isn't a known property of 'input'.

app.module.ts中已经导入了FormsModule并添加进了NgModule中。

**Comment by qpb** [comment]
问题已解决：
1.app.module.ts中去掉setup.module.ts的引用
2.app.module.ts中引入setup.component, 并且将SetupComponent添加至declarations中

猜测：setup.module.ts中引入了setup.component，且将setup.module添加至app.module.ts中并未生效，导致setup.component.html中的模板语法不能识别。

**Comment by wzhudev** [comment]
Angular 基础, 你需要在 SetupModule 里引入 FormsModule.

不要取消模块的划分, 划分模块有助于提高应用的可拓展性和可维护性.
