### ISSUE TITLE
按照指引文件有错，如何解决

### ISSUE THREAD

**Issue by keweiLv** [NG-ZORRO/today-ng-steps#29]
在指引文件中，`ervices/local-storage --module app`，执行这一步的时候，会报错：
`Unknown option: '--module'
Unknown option: 'app'
`，
即便我尝试添加flat也依旧如此。
这个问题该怎么解决呢

**Comment by wzhudev** [comment]
先阅读 https://angular.cn/guide/schematics 了解 schematics 的工作原理
