### ISSUE TITLE
建议修改文章内容，与当前版本ng-zorro和angular保持更新

### ISSUE THREAD

**Issue by Tonysmark** [NG-ZORRO/today-ng-steps#30]
希望作者能够明白这样做对于新手的好处，新手希望通过这篇文章快速上手ng-zorro 而不是因为版本的缘故卡在bug中，在此基础上能够希望作者考虑我的提议

**Comment by wzhudev** [comment]
@Tonysmark 在做了，没时间啊…… 😢

**Comment by Tonysmark** [comment]
加油！！！




------------------ 原始邮件 ------------------
发件人: "Wendell"<notifications@github.com>;
发送时间: 2019年8月6日(星期二) 下午5:35
收件人: "NG-ZORRO/today-ng-steps"<today-ng-steps@noreply.github.com>;
抄送: "Tonysmark"<mjyuyu@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [NG-ZORRO/today-ng-steps] 建议修改文章内容，与当前版本ng-zorro和angular保持更新 (#30)




@Tonysmark 在做了，没时间啊…… 😢

**Comment by wzhudev** [comment]
请关注 #17
