### ISSUE TITLE
第一章初始化local-storage时--module app无法使用

### ISSUE THREAD

**Issue by hanhan9449** [NG-ZORRO/today-ng-steps#37]
![image](https://user-images.githubusercontent.com/28822945/79204962-e8c64900-7e6f-11ea-9fa4-5ae29efc6da4.png)
将`--module app`删除可正常工作

node-version: 12.12.0-1
os-version: 5.6.3-2-MANJARO
npm-sersion: 6.14.4-1
ng-vserion: 9.0.1

**Comment by hanhan9449** [comment]
Unknown option: '--module'
Unknown option: 'app'

**Comment by wzhudev** [comment]
这应该是 @angular/cli 版本导致的？旧版教程撰写的时候 Angular 还是在 6 版本阶段。

如果可以麻烦请验证一下。

**Comment by hanhan9449** [comment]
[service](https://angular.io/cli/generate#service)
在最新的文档里面没有`--module`参数了，应该是@angular/cli的原因

**Comment by wzhudev** [comment]
Closed by #38.
